-- ============================================================
-- PASO 1: Agregar columna sort_order a ambas tablas
-- ============================================================
ALTER TABLE mano_de_obra ADD COLUMN IF NOT EXISTS sort_order INT DEFAULT 0;
ALTER TABLE refacciones  ADD COLUMN IF NOT EXISTS sort_order INT DEFAULT 0;

-- ============================================================
-- PASO 2: Limpiar todo
-- ============================================================
DELETE FROM mano_de_obra WHERE true;
DELETE FROM refacciones  WHERE true;

-- ============================================================
-- MANO DE OBRA — orden Excel: ELÉCTRICO → NEUMÁTICO → MECÁNICO
-- ============================================================
INSERT INTO mano_de_obra (sort_order, nombre, categoria, precio, activo) VALUES
(1,  'SERVICIO PREVENTIVO',                                                                     'ELÉCTRICO', 4250.00, true),
(2,  'CAMBIO Y RECONECTAR RELEY DE CORTE O VELOCIDAD /RELEVADOR)',                             'ELÉCTRICO', 300.00,  true),
(3,  'CAMBIO DE BULBO DE AIRE',                                                                 'ELÉCTRICO', 300.00,  true),
(4,  'CAMBIO PALANCA',                                                                          'ELÉCTRICO', 300.00,  true),
(5,  'CAMBIO CAJA DE CONTACTORES',                                                              'ELÉCTRICO', 600.00,  true),
(6,  'CAMBIO CAJA ELECTRONICA',                                                                 'ELÉCTRICO', 800.00,  true),
(7,  'CAMBIO DE FOCO PILOTO',                                                                   'ELÉCTRICO', 100.00,  true),
(8,  'REPARACION ARNES SENSOR VELOCIDAD',                                                       'ELÉCTRICO', 150.00,  true),
(9,  'CAMBIO DE SENSOR DE VELOCIDAD',                                                           'ELÉCTRICO', 350.00,  true),
(10, 'CAMBIO ARNES CORRIENTE (CAL 0) (CAJA CONTACTORES)(BATERIA POSITIVO)',                    'ELÉCTRICO', 250.00,  true),
(11, 'CAMBIO ARNES DE TIERRA (CAL 8) REPARACION DE MAZA NEGATIVO',                            'ELÉCTRICO', 250.00,  true),
(12, 'CAMBIO DE ARNES (7 VIAS)',                                                                'ELÉCTRICO', 800.00,  true),
(13, 'CAMBIO DE ARNES DE POTENCIA (4 VIAS)',                                                    'ELÉCTRICO', 350.00,  true),
(14, 'CAMBIO DE ARNES TIERRA (DE FRENO A BATERIAS) REP. O FAB. MAZA NEGATIVO',                'ELÉCTRICO', 250.00,  true),
(15, 'REPARACION DE ARNES DE CONTROL (CAMBIO DE TERMINALES) 4 LINEAS BLOCK CONEXION',         'ELÉCTRICO', 150.00,  true),
(16, 'SISTEMA DE CONTROL COMPLETO CAJA MECANICA',                                               'ELÉCTRICO', 2000.00, true),
(17, 'FABRICACION LINEAS SENSOR C/CONECTOR',                                                    'ELÉCTRICO', 150.00,  true),
(18, 'SISTEMA DE CONTROL COMPLETO CAJA ELECTRONICA',                                            'ELÉCTRICO', 2500.00, true),
(19, 'CAMBIO DE INTERRUPTOR',                                                                    'ELÉCTRICO', 150.00,  true),
(20, 'CAMBIO DE BLOCK CONEXIONES',                                                               'ELÉCTRICO', 400.00,  true),
(21, 'REPARACION LINEAS DE TABLERO',                                                             'ELÉCTRICO', 200.00,  true),
(22, 'REPARACION LINEAS DE TABLERO ALIMENTACION O PORT FUSIBLE',                                'ELÉCTRICO', 200.00,  true),
(23, 'REPARACION ARNES DE 7 VIAS (SIN Realizar cambio completo)',                               'ELÉCTRICO', 250.00,  true),
(24, 'REPARACION CAJA CONTACTORES',                                                              'ELÉCTRICO', 300.00,  true),
(25, 'CAMBIO DE MEGA FUSIBLE O PORTA MEGA FUSIBLE',                                             'ELÉCTRICO', 200.00,  true),
(26, 'INSTALACION DE SISTEMA ELECTRICO COMPLETO',                                               'ELÉCTRICO', 3000.00, true),
(27, 'REVISION DE CONSUMOS',                                                                     'ELÉCTRICO', 500.00,  true),
(28, 'INSTALACION SISTEMA NEUMATICO',                                                            'NEUMÁTICO', 1000.00, true),
(29, 'REPARACION SISTEMA NEUMATICO (BULBO)',                                                     'NEUMÁTICO', 300.00,  true),
(30, 'CAMBIO MANGUERA',                                                                          'NEUMÁTICO', 250.00,  true),
(31, 'KIT DE LUCES LED',                                                                         'NEUMÁTICO', 4250.00, true),
(32, 'LIMPIEZA DE FRENOS SIN DESARMAR',                                                          'MECÁNICO',  400.00,  true),
(33, 'INSTALACION MECANICA O REINSTALACION DE FRENO',                                           'MECÁNICO',  3500.00, true),
(34, 'SOLO BAJAR PURO FRENO',                                                                    'MECÁNICO',  1500.00, true),
(35, 'CAMBIO DE SOPORTE DE CHASIS TIPO L C/U',                                                  'MECÁNICO',  400.00,  true),
(36, 'CAMBIO DE ROTOR FRENO INSTALADO C/U',                                                     'MECÁNICO',  600.00,  true),
(37, 'MONTAJE DE FRENO (AXIAL) COMPLETO CON KIT DE CONTROL',                                    'MECÁNICO',  6000.00, true),
(38, 'CAMBIO DE SILENTBLOKS',                                                                    'MECÁNICO',  2500.00, true),
(39, 'CAMBIO DE RETEN DE FRENO',                                                                 'MECÁNICO',  700.00,  true),
(40, 'CAMBIO O REPARARCION DE ARNES INTERIOR (CONEXION)',                                        'MECÁNICO',  500.00,  true),
(41, 'BAJAR CARDANES Y DESCONECTAR ARNESES DE FRENO',                                           'MECÁNICO',  750.00,  true),
(42, 'MONTAJE DE CARDANES Y ARNESES DE FRENO',                                                  'MECÁNICO',  750.00,  true),
(43, 'CAMBIO DE PLACAS LATERALES C/U',                                                           'MECÁNICO',  300.00,  true),
(44, 'DESARMADO DE FRENO QUITANDO BOBINAS (SIEMPRE Y CUANDO SALGAN)',                           'MECÁNICO',  1000.00, true),
(45, 'REPARACION DE FRENO (BALEROS, RETENES Y CASQUILLOS, REPARACION ARMADO) SIN BOBINAS',     'MECÁNICO',  2500.00, true),
(46, 'CAMBIO O REPARACION ARNES INTERIOR (CONEXION)',                                            'MECÁNICO',  500.00,  true),
(47, 'CAMBIO KIT DE ENGRASE SISTEMA DE LUBRICACION',                                             'MECÁNICO',  570.00,  true),
(48, 'CAMBIO DE 1 KIT DE REPARACION DE BOBINA',                                                 'MECÁNICO',  200.00,  true),
(49, 'REPARACION DE CUERDA DE FRENO O PLACA LATERAL C/U',                                      'MECÁNICO',  100.00,  true),
(50, 'REFRESCO CUERDAS DE TORNILLOS DE CRUCETA C/U',                                            'MECÁNICO',  100.00,  true),
(51, 'CAMBIO SEGUROS DE CRUCETAS',                                                               'MECÁNICO',  200.00,  true),
(52, 'CAMBIO DE CRUCETA',                                                                        'MECÁNICO',  500.00,  true),
(53, 'CAMBIO DE BOBINA C/U',                                                                     'MECÁNICO',  300.00,  true),
(54, 'CAMBIO DE PLACA POLAR C/U',                                                                'MECÁNICO',  200.00,  true),
(55, 'CALIBRACION ENTRE HIERRO ROTOR',                                                           'MECÁNICO',  550.00,  true),
(56, 'BAJAR Y SUBIR CARDANES LADO DE FRENO CAJA Y DIFERENCIAL',                                 'MECÁNICO',  1500.00, true),
(57, 'CAMBIO TORNILLO PLATO ACOPLE C/U',                                                         'MECÁNICO',  75.00,   true),
(58, 'DESINSTALACION FRENO (CON ARNES)',                                                         'MECÁNICO',  2500.00, true),
(59, 'CAMBIO DE TERMINALES',                                                                     'MECÁNICO',  200.00,  true),
(60, 'RECONEXION ELECTRICA',                                                                     'MECÁNICO',  200.00,  true),
(61, 'SUBIR FRENO',                                                                              'MECÁNICO',  750.00,  true),
(62, 'CAMBIO CORTA CORRIENTE',                                                                   'MECÁNICO',  350.00,  true);

-- ============================================================
-- SOPORTERÍA
-- ============================================================
INSERT INTO refacciones (sort_order, nombre, categoria, precio_venta, activo) VALUES
(1,  'Placas 330 X 400 (PK-PK1)',                        'SOPORTERÍA', 3587.50, true),
(2,  'Albardon de 120 X 120 (PK-PK1)',                   'SOPORTERÍA', 5.00,    true),
(3,  'Albardon 70 x 140 (PK-PK1)',                       'SOPORTERÍA', 0.00,    true),
(4,  'Placa Soporte chasis 3/8X100X160X240MM C/CAR',     'SOPORTERÍA', 975.00,  true),
(5,  'Juego Silenblocks (PK-PK1)',                       'SOPORTERÍA', 2172.95, true),
(6,  'Tornillos 5/16 X 1 (PK-PK1)',                     'SOPORTERÍA', 3.75,    true),
(7,  'Tuercas Seguridad 5/16 (PK-PK1)',                  'SOPORTERÍA', 2.00,    true),
(8,  'Arandela Presion 5/16 (PK-PK1)',                   'SOPORTERÍA', 0.75,    true),
(9,  'Tornillos 5/16 X 2 (PK-PK1)',                     'SOPORTERÍA', 5.00,    true),
(10, 'Tornillos 12MM x 50mm',                            'SOPORTERÍA', 25.00,   true),
(11, 'Tuercas Seguridad 12MM',                           'SOPORTERÍA', 13.75,   true),
(12, 'Arandela Automotiva 1/2 x1',                       'SOPORTERÍA', 8.13,    true),
(13, 'Arandela Grande 1/2 X 2',                          'SOPORTERÍA', 30.00,   true),
(14, 'Tornillo 14 mm (PK-PK1)',                          'SOPORTERÍA', 20.63,   true),
(15, 'Arandelas presion 9/16 (PK-PK1)',                  'SOPORTERÍA', 3.13,    true),
(16, 'Tornillo 18mm X 50 (PK-PK1)',                      'SOPORTERÍA', 43.13,   true),
(17, 'Tuerca Seguridad 18mm (PK-PK1)',                   'SOPORTERÍA', 18.75,   true),
(18, 'Placas 330 X 400 (P5-P51)',                        'SOPORTERÍA', 3250.00, true),
(19, 'Albardon de 120 X 120 (P5-P51)',                   'SOPORTERÍA', 0.00,    true),
(20, 'Albardon 70 x 140 (P5-P51)',                       'SOPORTERÍA', 0.00,    true),
(21, 'Placa Soporte chasis (P5-P51)',                    'SOPORTERÍA', 1025.00, true),
(22, 'Juego Silenblocks (P5-P51)',                       'SOPORTERÍA', 0.00,    true),
(23, 'Tornillos 5/16 X 1 (P5-P51)',                     'SOPORTERÍA', 3.75,    true),
(24, 'Tuercas Seguridad 5/16 (P5-P51)',                  'SOPORTERÍA', 2.00,    true),
(25, 'Arandela Presion 5/16 (P5-P51)',                   'SOPORTERÍA', 0.75,    true),
(26, 'Tornillos 5/16 X 2 (P5-P51)',                     'SOPORTERÍA', 5.00,    true),
(27, 'Tornillos 18mm X 120mm grado 9.8 paso 1.50 (P5)', 'SOPORTERÍA', 140.00,  true),
(28, 'Tuercas Seguridad 18mm paso 1.50 (P5)',            'SOPORTERÍA', 18.75,   true),
(29, 'Arandela Automotiva 3/4 (P5)',                     'SOPORTERÍA', 12.50,   true),
(30, 'Arandela Grande 3/4 x 2.5 (P5)',                  'SOPORTERÍA', 30.00,   true),
(31, 'Tornillo 14 mm (P5-P51)',                          'SOPORTERÍA', 20.63,   true),
(32, 'Arandelas presion 9/16 (P5-P51)',                  'SOPORTERÍA', 3.13,    true),
(33, 'Tornillo 18mm X 50 (P5-P51)',                      'SOPORTERÍA', 43.13,   true),
(34, 'Tuerca Seguridad 18mm (P5-P51)',                   'SOPORTERÍA', 18.75,   true),
(35, 'Placas 330 X 400 (P7)',                            'SOPORTERÍA', 2860.00, true),
(36, 'Albardon de 120 X 120 (P7)',                       'SOPORTERÍA', 0.00,    true),
(37, 'Albardon 70 x 140 (P7)',                           'SOPORTERÍA', 0.00,    true),
(38, 'Placa Soporte chasis (P7)',                        'SOPORTERÍA', 902.00,  true),
(39, 'Juego Silenblocks (P7)',                           'SOPORTERÍA', 2172.96, true),
(40, 'Tornillos 5/16 X 1 (P7)',                         'SOPORTERÍA', 3.75,    true),
(41, 'Tuercas Seguridad 5/16 (P7)',                      'SOPORTERÍA', 2.00,    true),
(42, 'Arandela Presion 5/16 (P7)',                       'SOPORTERÍA', 0.75,    true),
(43, 'Tornillos 5/16 X 2 (P7)',                         'SOPORTERÍA', 5.00,    true),
(44, 'Tornillos 18mm X 120mm grado 9.8 paso 1.50 (P7)', 'SOPORTERÍA', 140.00,  true),
(45, 'Tuercas Seguridad 18mm paso 1.50 (P7)',            'SOPORTERÍA', 18.75,   true),
(46, 'Arandela Automotiva 3/4 (P7)',                     'SOPORTERÍA', 12.50,   true),
(47, 'Arandela Grande 3/4 x 2.5 (P7)',                  'SOPORTERÍA', 30.00,   true),
(48, 'Tornillo 14 mm (P7)',                              'SOPORTERÍA', 20.63,   true),
(49, 'Arandelas presion 9/16 (P7)',                      'SOPORTERÍA', 3.13,    true),
(50, 'Tornillo 18mm X 50 (P7)',                          'SOPORTERÍA', 43.13,   true),
(51, 'Tuerca Seguridad 18mm (P7)',                       'SOPORTERÍA', 18.75,   true),
(52, 'Placas 330 X 400 (P10)',                           'SOPORTERÍA', 3887.50, true),
(53, 'Albardon de 120 X 120 (P10)',                      'SOPORTERÍA', 0.00,    true),
(54, 'Albardon 70 x 140 (P10)',                          'SOPORTERÍA', 0.00,    true),
(55, 'Placa Soporte chasis (P10)',                       'SOPORTERÍA', 1025.00, true),
(56, 'Juego Silenblocks (P10)',                          'SOPORTERÍA', 0.00,    true),
(57, 'Tornillos 5/16 X 1 (P10)',                        'SOPORTERÍA', 3.75,    true),
(58, 'Tuercas Seguridad 5/16 (P10)',                     'SOPORTERÍA', 2.00,    true),
(59, 'Arandela Presion 5/16 (P10)',                      'SOPORTERÍA', 0.75,    true),
(60, 'Tornillos 5/16 X 2 (P10)',                        'SOPORTERÍA', 5.00,    true),
(61, 'Tornillos 18mm X 125mm (P10)',                     'SOPORTERÍA', 140.00,  true),
(62, 'Tuercas Seguridad 18mm (P10)',                     'SOPORTERÍA', 18.75,   true),
(63, 'Arandela Automotiva 3/4 (P10)',                    'SOPORTERÍA', 12.50,   true),
(64, 'Arandela Grande 3/4 x 2.5 (P10)',                 'SOPORTERÍA', 30.00,   true),
(65, 'Tornillo 14 mm (P10)',                             'SOPORTERÍA', 20.63,   true),
(66, 'Arandelas presion 9/16 (P10)',                     'SOPORTERÍA', 3.13,    true),
(67, 'Tornillo 18mm X 50 (P10)',                         'SOPORTERÍA', 43.13,   true),
(68, 'Tuerca Seguridad 18mm (P10)',                      'SOPORTERÍA', 18.75,   true),
(69, 'Placas Base 6X260X255MM',                          'SOPORTERÍA', 575.00,  true),
(70, 'Placa soporte 6X260X147',                          'SOPORTERÍA', 825.00,  true),
(71, 'Albardon de 8X80X50MM',                            'SOPORTERÍA', 37.50,   true),
(72, 'Albardon 8mmX140X70MM',                            'SOPORTERÍA', 87.50,   true),
(73, 'Placa Soporte chasis 3/8X100X160X240 CON CAR',     'SOPORTERÍA', 975.00,  true),
(74, 'Juego Silenblocks (F16-80)',                       'SOPORTERÍA', 5521.66, true),
(75, 'Tornillos 5/16 X 1 (F16-80)',                     'SOPORTERÍA', 3.75,    true),
(76, 'Tuercas Seguridad 5/16 (F16-80)',                  'SOPORTERÍA', 2.00,    true),
(77, 'Arandela Presion 5/16 (F16-80)',                   'SOPORTERÍA', 0.75,    true),
(78, 'Tornillos 5/16 X 2 (F16-80)',                     'SOPORTERÍA', 5.00,    true),
(79, 'Tornillos 1/2 X 4',                               'SOPORTERÍA', 25.00,   true),
(80, 'Tuercas Seguridad 1/2',                            'SOPORTERÍA', 13.75,   true),
(81, 'Arandela Automotiva 1/2 x1 (F16-80)',              'SOPORTERÍA', 8.13,    true),
(82, 'Arandela Grande 1/2 X 2 (F16-80)',                 'SOPORTERÍA', 30.00,   true),
(83, 'Tornillo 14 mm (F16-80)',                          'SOPORTERÍA', 20.63,   true),
(84, 'Arandelas presion 9/16 (F16-80)',                  'SOPORTERÍA', 3.13,    true),
(85, 'Tornillo 18mm X 50 (F16-80)',                      'SOPORTERÍA', 43.13,   true),
(86, 'Tuerca Seguridad 18mm (F16-80)',                   'SOPORTERÍA', 18.75,   true),
(87, 'Placas 8X400X365MM',                               'SOPORTERÍA', 1062.50, true),
(88, 'Placa Soporte chasis8x 400x100',                   'SOPORTERÍA', 1050.00, true),
(89, 'Albardon de 8X140X70MM',                           'SOPORTERÍA', 87.50,   true),
(90, 'Albardon 8X80X50MM',                               'SOPORTERÍA', 37.50,   true),
(91, 'Placa Soporte chasis 3/8X120X140X170CON CART.',    'SOPORTERÍA', 1025.00, true),
(92, 'Juego Silenblocks (F16-200)',                      'SOPORTERÍA', 5160.63, true),
(93, 'Tornillos 5/16 X 1 (F16-200)',                    'SOPORTERÍA', 3.75,    true),
(94, 'Tuercas Seguridad 5/16 (F16-200)',                 'SOPORTERÍA', 2.00,    true),
(95, 'Arandela Presion 5/16 (F16-200)',                  'SOPORTERÍA', 0.75,    true),
(96, 'Tornillos 5/16 X 2 (F16-200)',                    'SOPORTERÍA', 5.00,    true),
(97, 'Tornillos 18mm X 125mm (F16-200)',                 'SOPORTERÍA', 140.00,  true),
(98, 'Tuercas Seguridad 18mm (F16-200)',                 'SOPORTERÍA', 18.75,   true),
(99, 'Arandela Automotiva 3/4 (F16-200)',                'SOPORTERÍA', 12.50,   true),
(100,'Arandela Grande 3/4 x 2.5 (F16-200)',              'SOPORTERÍA', 30.00,   true),
(101,'Tornillo 14 mm (F16-200)',                          'SOPORTERÍA', 20.63,   true),
(102,'Arandelas presion 9/16 (F16-200)',                  'SOPORTERÍA', 3.13,    true),
(103,'Tornillo 18mm X 50 (F16-200)',                      'SOPORTERÍA', 43.13,   true),
(104,'Tuerca Seguridad 18mm (F16-200)',                   'SOPORTERÍA', 18.75,   true);

-- ============================================================
-- CARDANES
-- ============================================================
INSERT INTO refacciones (sort_order, nombre, categoria, precio_venta, activo) VALUES
(1,  'Soldable 1480 para tubo 3342mm',         'CARDANES', 600.00,   true),
(2,  'Espiga 1480 para tubo 3342mm',           'CARDANES', 1375.00,  true),
(3,  'Deslizable 1480 para tubo 3342',         'CARDANES', 1625.00,  true),
(4,  'Cruceta 1480',                           'CARDANES', 312.50,   true),
(5,  'Plato Brida para 1480',                  'CARDANES', 637.50,   true),
(6,  'Soldable 1550',                          'CARDANES', 750.75,   true),
(7,  'Espiga 1550',                            'CARDANES', 1251.25,  true),
(8,  'Deslizable 1550',                        'CARDANES', 1278.88,  true),
(9,  'Cruceta 1550',                           'CARDANES', 253.50,   true),
(10, 'Plato Brida para 1550',                  'CARDANES', 755.63,   true),
(11, 'Soldable 1610',                          'CARDANES', 1062.50,  true),
(12, 'Espiga 1610',                            'CARDANES', 1937.50,  true),
(13, 'Deslizable 1610',                        'CARDANES', 3000.00,  true),
(14, 'Cubrepolvo 1610',                        'CARDANES', 0.00,     true),
(15, 'Cruceta 1610',                           'CARDANES', 565.50,   true),
(16, 'Plato Brida para 1610',                  'CARDANES', 2437.50,  true),
(17, 'Tornillos 3/8 X 1.5 cuerda fina (1610)','CARDANES', 7.50,     true),
(18, 'Tuercas cuerda fina 3/8 (1610)',         'CARDANES', 5.00,     true),
(19, 'Soldable 1710',                          'CARDANES', 1250.00,  true),
(20, 'Espiga 1710',                            'CARDANES', 2375.00,  true),
(21, 'Deslizable 1710',                        'CARDANES', 3125.00,  true),
(22, 'Cubrepolvo 1710',                        'CARDANES', 419.25,   true),
(23, 'Cruceta 1710',                           'CARDANES', 812.50,   true),
(24, 'Plato Brida para 1710',                  'CARDANES', 2437.50,  true),
(25, 'Tornillos 3/8 X 1.5 cuerda fina (1710)','CARDANES', 7.50,     true),
(26, 'Tuercas cuerda fina 3/8 (1710)',         'CARDANES', 5.00,     true),
(27, 'Soldable 1810',                          'CARDANES', 2125.00,  true),
(28, 'Espiga 1810',                            'CARDANES', 3250.00,  true),
(29, 'Deslizable 1810',                        'CARDANES', 4687.50,  true),
(30, 'Cubrepolvo 1810',                        'CARDANES', 723.13,   true),
(31, 'Cruceta 1810',                           'CARDANES', 937.50,   true),
(32, 'Plato Brida para 1810',                  'CARDANES', 2562.50,  true),
(33, 'Tornillos 7/16 X 1.5 cuerda fina',      'CARDANES', 13.75,    true),
(34, 'Tuercas cuerda fina 7/16',               'CARDANES', 7.50,     true),
(35, 'Soldable SPL250',                        'CARDANES', 625.00,   true),
(36, 'Yugo Espiga SPL250',                     'CARDANES', 3125.00,  true),
(37, 'Camisa SPL250',                          'CARDANES', 6375.00,  true),
(38, 'Cubrepolvo SPL250',                      'CARDANES', 1875.00,  true),
(39, 'Cruceta SPL250',                         'CARDANES', 1500.00,  true),
(40, 'Plato Brida para SPL250',                'CARDANES', 15500.00, true),
(41, 'Seguros Cruceta SPL250',                 'CARDANES', 750.00,   true),
(42, 'Plato Brida para 1480 (15%)',            'CARDANES', 637.50,   true),
(43, 'Plato Brida para 1550 (15%)',            'CARDANES', 695.18,   true),
(44, 'Plato Brida para 1610 (15%)',            'CARDANES', 2242.50,  true),
(45, 'Plato Brida para 1710 (15%)',            'CARDANES', 2242.50,  true),
(46, 'Plato Brida para 1810 (15%)',            'CARDANES', 2357.50,  true),
(47, 'Plato Brida para SPL250 (15%)',          'CARDANES', 14260.00, true);

-- ============================================================
-- MATERIAL ELÉCTRICO
-- ============================================================
INSERT INTO refacciones (sort_order, nombre, categoria, precio_venta, activo) VALUES
(1,  'CAJA MECANICA',                                          'MATERIAL ELÉCTRICO', 15638.96, true),
(2,  'CAJA ELECTRONICA',                                       'MATERIAL ELÉCTRICO', 16708.29, true),
(3,  'PALANCA CONTROL',                                        'MATERIAL ELÉCTRICO', 4253.86,  true),
(4,  'RELAY DE CORTE DE VELOCIDAD',                            'MATERIAL ELÉCTRICO', 7322.66,  true),
(5,  'CABLE 4 VIAS',                                           'MATERIAL ELÉCTRICO', 308.63,   true),
(6,  'CABLE CALIBRE 0 CORRIENTE GRUESO 01X2AWG 35mm2',         'MATERIAL ELÉCTRICO', 272.48,   true),
(7,  'CABLE CALIBRE 0 TIERRA DELGADO 01X4AWG 25mm2',           'MATERIAL ELÉCTRICO', 133.67,   true),
(8,  'CABLE 7 VIAS',                                           'MATERIAL ELÉCTRICO', 174.50,   true),
(9,  'FOCO PILOTO',                                            'MATERIAL ELÉCTRICO', 217.50,   true),
(10, 'KIT DE TERMINALES',                                      'MATERIAL ELÉCTRICO', 915.07,   true),
(11, 'TORNILLOS SUJECION DE CAJA 5/16 x1/2',                  'MATERIAL ELÉCTRICO', 6.25,     true),
(12, 'TUERCAS SUJECION DE CAJA 5/16 x1/2',                    'MATERIAL ELÉCTRICO', 2.49,     true),
(13, 'ARANDELAS DE PRESION 5/16 x1/2',                        'MATERIAL ELÉCTRICO', 2.49,     true),
(14, 'CABLE CALIBRE 14',                                       'MATERIAL ELÉCTRICO', 11.37,    true),
(15, 'CABLE NEGATIVO CALIBRE 8',                               'MATERIAL ELÉCTRICO', 58.01,    true),
(16, 'SENSOR DE ROSCA 4 VIAS',                                 'MATERIAL ELÉCTRICO', 2411.31,  true),
(17, 'ARNES DE SENSOR ROSCA 4 VIAS',                           'MATERIAL ELÉCTRICO', 435.00,   true),
(18, 'MANTA FOIL',                                             'MATERIAL ELÉCTRICO', 118.39,   true),
(19, 'INTERRUPTOR COLA RATA REFORZADO',                        'MATERIAL ELÉCTRICO', 346.43,   true),
(20, 'CONECTOR 4 VIAS SENSOR DE CLIP',                         'MATERIAL ELÉCTRICO', 435.00,   true),
(21, 'FUSIBLE 1AMP',                                           'MATERIAL ELÉCTRICO', 14.50,    true),
(22, 'FUSIBLE 5 AMP',                                          'MATERIAL ELÉCTRICO', 14.50,    true),
(23, 'FUSIBLE 300 AMP',                                        'MATERIAL ELÉCTRICO', 217.50,   true),
(24, 'PORTAFUSIBLE',                                           'MATERIAL ELÉCTRICO', 139.88,   true),
(25, 'POLIFLEX 1/2',                                           'MATERIAL ELÉCTRICO', 16.48,    true),
(26, 'POLIFLEX 1/4',                                           'MATERIAL ELÉCTRICO', 8.19,     true),
(27, 'POLIFLEX 3/4',                                           'MATERIAL ELÉCTRICO', 21.46,    true),
(28, 'POLIFLEX 3/8',                                           'MATERIAL ELÉCTRICO', 10.71,    true),
(29, 'CINCHOS',                                                'MATERIAL ELÉCTRICO', 2.88,     true),
(30, 'CINTA DE AISLAR NEGRA',                                  'MATERIAL ELÉCTRICO', 20.66,    true),
(31, 'CINTA DE AISLAR ROJA',                                   'MATERIAL ELÉCTRICO', 20.66,    true),
(32, 'PINTURA NEGRA',                                          'MATERIAL ELÉCTRICO', 170.52,   true),
(33, 'ALMEJA',                                                 'MATERIAL ELÉCTRICO', 7.25,     true),
(34, 'TERMINAL DE OJILLO 5/16 CAL 14',                         'MATERIAL ELÉCTRICO', 1.31,     true),
(35, 'TERMINAL DEL 8 CAL 10',                                  'MATERIAL ELÉCTRICO', 7.25,     true),
(36, 'TERMINAL ENCHUFE FORRADA ROJA',                          'MATERIAL ELÉCTRICO', 2.03,     true),
(37, 'TERMINAL ESPADA CALIBRE 14',                             'MATERIAL ELÉCTRICO', 1.45,     true),
(38, 'TERMINAL OJILLO AZUL 1/4 MASA CAJA CONTACTORES',         'MATERIAL ELÉCTRICO', 1.51,     true),
(39, 'TERMINALES DE OJILLO CAL 0 5/16',                        'MATERIAL ELÉCTRICO', 15.20,    true),
(40, 'TERMINALES DE OJILLO CAL 0 3/8',                         'MATERIAL ELÉCTRICO', 15.95,    true),
(41, 'TERMO CONTRACTIL 3/8',                                   'MATERIAL ELÉCTRICO', 10.88,    true),
(42, 'TERMOCONTRACTIL 3/4',                                    'MATERIAL ELÉCTRICO', 36.25,    true),
(43, 'TOPES CONECTOR',                                         'MATERIAL ELÉCTRICO', 1.73,     true),
(44, 'CORTA CORRIENTE 250 AMP',                                'MATERIAL ELÉCTRICO', 1015.00,  true),
(45, 'CORTA CORRIENTE 300 AMP',                                'MATERIAL ELÉCTRICO', 1342.24,  true),
(46, 'PORTAMEGAFUSIBLE',                                       'MATERIAL ELÉCTRICO', 725.00,   true),
(47, 'MEGAFUSIBLE 300 AMP',                                    'MATERIAL ELÉCTRICO', 531.16,   true),
(48, 'RELAY HELLA 12 VOLT',                                    'MATERIAL ELÉCTRICO', 187.34,   true),
(49, 'RELAY HELLA 24 VOLT',                                    'MATERIAL ELÉCTRICO', 232.00,   true),
(50, 'PORTA RELE HELLA',                                       'MATERIAL ELÉCTRICO', 116.00,   true),
(51, 'LUZ LED VERDE',                                          'MATERIAL ELÉCTRICO', 343.48,   true),
(52, 'SENSOR DE ROSCA DE 2 VIAS',                              'MATERIAL ELÉCTRICO', 1620.33,  true),
(53, 'SENSOR DE VELOCIDAD CLIP 2 VIAS',                        'MATERIAL ELÉCTRICO', 1775.67,  true),
(54, 'SENSOR DE VELOCIDAD CLIP 4 VIAS',                        'MATERIAL ELÉCTRICO', 2632.20,  true),
(55, 'FUSIBLE CAJAS',                                          'MATERIAL ELÉCTRICO', 58.00,    true),
(56, 'GRASERA RECTA DE 3/8',                                   'MATERIAL ELÉCTRICO', 33.06,    true),
(57, 'KIT REPARACION BOBINA DE COBRE',                         'MATERIAL ELÉCTRICO', 343.48,   true),
(58, 'CONEXION NEUMATICA 1/4',                                 'MATERIAL ELÉCTRICO', 254.40,   true),
(59, 'CONEXION T NEUMATICA 1/4',                               'MATERIAL ELÉCTRICO', 469.80,   true),
(60, 'MANGUERA DE 1/4',                                        'MATERIAL ELÉCTRICO', 113.44,   true),
(61, 'CONEXION NEUMATICA 3/8',                                 'MATERIAL ELÉCTRICO', 275.50,   true),
(62, 'CONEXION T NEUMATICA 3/8',                               'MATERIAL ELÉCTRICO', 783.00,   true),
(63, 'MANGUERA 3/8',                                           'MATERIAL ELÉCTRICO', 156.60,   true),
(64, 'REDUCCION BUSHING 3/8 A 1/4',                            'MATERIAL ELÉCTRICO', 52.93,    true),
(65, 'BULBO DE AIRE HOBS',                                     'MATERIAL ELÉCTRICO', 4227.69,  true),
(66, 'KIT LUCES LED COMPLETO',                                 'MATERIAL ELÉCTRICO', 4930.00,  true);

-- ============================================================
-- TORNILLERÍA
-- ============================================================
INSERT INTO refacciones (sort_order, nombre, categoria, precio_venta, activo) VALUES
(1,  'Tornillos de 5/16 X 1',                          'TORNILLERÍA', 3.75,   true),
(2,  'Tuercas de Seguridad 5/16',                       'TORNILLERÍA', 2.00,   true),
(3,  'Arandela de Presion de 5/16',                     'TORNILLERÍA', 0.75,   true),
(4,  'Tornillos de 5/16 X 2',                          'TORNILLERÍA', 5.00,   true),
(5,  'Tornillos de 12MM x 90mm',                        'TORNILLERÍA', 25.00,  true),
(6,  'Tuercas de Seguridad 12MM',                       'TORNILLERÍA', 13.75,  true),
(7,  'Arandela Automotiva de 1/2 x1',                   'TORNILLERÍA', 8.13,   true),
(8,  'Arandela Grande de 1/2 X 2',                      'TORNILLERÍA', 30.00,  true),
(9,  'Tornillo 14 mm',                                  'TORNILLERÍA', 20.63,  true),
(10, 'Arandelas de presion 9/16',                       'TORNILLERÍA', 3.13,   true),
(11, 'Tornillo 18mm X 50',                              'TORNILLERÍA', 43.13,  true),
(12, 'Tuerca de Seguridad 18mm',                        'TORNILLERÍA', 18.75,  true),
(13, 'Tornillos de 18mm X 120mm grado 9.8 paso 1.50',  'TORNILLERÍA', 140.00, true),
(14, 'Tuercas de Seguridad 18mm paso 1.50',             'TORNILLERÍA', 18.75,  true),
(15, 'Arandela Automotiva de 3/4',                      'TORNILLERÍA', 12.50,  true),
(16, 'Arandela Grande de 3/4 x 2.5',                   'TORNILLERÍA', 30.00,  true),
(17, 'Tornillos de 18mm X 125mm',                       'TORNILLERÍA', 140.00, true),
(18, 'Tornillo 3/4 X 2',                               'TORNILLERÍA', 42.50,  true),
(19, 'Tuerca de Seguridad 3/4',                         'TORNILLERÍA', 47.75,  true),
(20, 'Tornillos de 1/2 X 4',                           'TORNILLERÍA', 25.00,  true),
(21, 'Tuercas de Seguridad 1/2',                        'TORNILLERÍA', 13.75,  true),
(22, 'JUEGO DE SILENBLOCK MARCA KLAM',                  'MECÁNICO',    0.00,   true);

-- ============================================================
SELECT tabla, categoria, COUNT(*) total FROM (
  SELECT 'mano_de_obra' tabla, categoria FROM mano_de_obra
  UNION ALL
  SELECT 'refacciones' tabla, categoria FROM refacciones
) t GROUP BY tabla, categoria ORDER BY tabla, categoria;
